steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/deakin-capstone-224848845/deakin-resource-api:v6-trigger'
      - './Task-7.2HD-Individual_Capstone_Project'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/deakin-capstone-224848845/deakin-resource-api:v6-trigger'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    args:
      - 'set'
      - 'image'
      - 'deployment/deakin-resource-api'
      - 'deakin-resource-api=australia-southeast1-docker.pkg.dev/$PROJECT_ID/deakin-capstone-224848845/deakin-resource-api:v6-trigger'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=sit737-cluster-capstone-project'

options:
  logging: NONE