steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/deakin-capstone-224848845/deakin-resource-api:v5-cloudbuild'
      - './Task-7.2HD-Individual_Capstone_Project'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    args:
      - 'push'
      - 'australia-southeast1-docker.pkg.dev/$PROJECT_ID/deakin-capstone-224848845/deakin-resource-api:v5-cloudbuild'

  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'Deploy to GKE'
    args:
      - 'run'
      - '--filename=Task-7.2HD-Individual_Capstone_Project/k8s'
      - '--image=australia-southeast1-docker.pkg.dev/$PROJECT_ID/deakin-capstone-224848845/deakin-resource-api:v5-cloudbuild'
      - '--location=australia-southeast1-a'
      - '--cluster=sit737-cluster-capstone-project'

options:
  logging: CLOUD_LOGGING_ONLY