steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Docker Image'
    args:
      - 'build'
      - '-t'
      - 'ashanin24x7/deakin-resource-api:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Docker Image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DOCKER_PASSWORD" | docker login -u "$$DOCKER_USERNAME" --password-stdin
        docker push ashanin24x7/deakin-resource-api:latest
    secretEnv:
      - 'DOCKER_USERNAME'
      - 'DOCKER_PASSWORD'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy to GKE'
    args:
      - 'set'
      - 'image'
      - 'deployment/deakin-resource-api'
      - 'deakin-resource-api=ashanin24x7/deakin-resource-api:latest'

    env:
      - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=sit737-cluster-capstone-project'

options:
  logging: CLOUD_LOGGING_ONLY